spring.application.name=backend
server.port=8081
server.address=localhost
loadbalancer.url=http://localhost:8080
management.endpoints.web.exposure.include=health,info,metrics
spring.docker.compose.enabled=false